# Generated by Django 4.2.5 on 2023-09-25 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moneymanagerapp', '0004_incomecategory_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='attachment',
        ),
        migrations.AddField(
            model_name='transfer',
            name='transfer_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='moneymanagerapp.incomecategory'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='withdrawed_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='moneymanagerapp.account'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='income',
            name='deposited_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='moneymanagerapp.account'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TransferCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_category', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.ImageField(upload_to='transaction_images/')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moneymanagerapp.transaction')),
            ],
        ),
    ]
