# Generated by Django 4.2.5 on 2023-10-19 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moneymanagerapp', '0005_remove_transaction_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acc_expense', to='moneymanagerapp.expensecategory'),
        ),
        migrations.AlterField(
            model_name='income',
            name='income_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acc_income', to='moneymanagerapp.incomecategory'),
        ),
    ]
