# Generated by Django 4.2.8 on 2024-02-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneymanagerapp', '0008_rename_expense_category_expense_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='category_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='incomecategory',
            name='category_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='label',
            name='label_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='settlementstatus',
            name='status',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='transfercategory',
            name='category_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
