# Generated by Django 4.2.10 on 2024-03-14 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneymanagerapp', '0010_rename_budget_budget_max_budget_user_goal_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='max',
            new_name='budget',
        ),
    ]
